### ISSUE TITLE
Board will not boot when bltouch is connected to servo ports

### ISSUE THREAD

**Issue by Trevor159** [gazcbm/Marlin-2.0.x-SKR-Mini-E3-v1.2#4]
I understand this is not your issue at all but I thought you might understand this a little more than me. 

https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/43

This is the issue I made on the official github repo but my v1.2 board only shows backlight when the bltouch is connected to the servo ports. Maybe I am stupid but this seems like a hardware issue and not a software issue from my observations but I might just be dumb.

EDIT: I have an official v3.1 bltouch

**Comment by gazcbm** [comment]
What colour is your middle pin on the dupont connector?

**Comment by Trevor159** [comment]
Solved: the wiring diagram for the creality bltouch in your readme had the red and blue wires flipped. I had a creality v3.1 fwiw

**Comment by gazcbm** [comment]
Wow it seems like creality have many different flavours of wiring.  Thanks for the headsup, I will add your info to the readme
